---
title: "Untitled"
output: html_document
date: "2023-11-15"
---

```{r,message=FALSE}
#install required packages the first time you use this code
#install.packages('tidyverse')
#install.packages('tidycensus')
#install.packages('censusapi')
#install.packages('stringr')

#load required packages
library(tidyverse)
library(tidycensus)
library(censusapi)
library(stringr)
```

```{r}
#metadata for available variables
#acs_vars <- listCensusMetadata(name="2018/acs/acs5",
                               #type="variables")


#metadata for available geographies
#acs_geos <- listCensusMetadata(name="2018/acs/acs5",
                              # type="geography")


#county and state names that match fips codes (from tidycensus package)
fips <- fips_codes

#import tribal fips code (from file on local drive)
fips_tribal <- read.csv("../Input/AIANNHCE Codes.csv")

```


### County Data for No Health Insurance
```{r}
countydata <- getCensus(name="acs/acs5/subject",
          vintage=2022,
          key=Sys.getenv("CENSUS_API_KEY"),
          vars=c("S2701_C05_001E","S2701_C05_001M"),
          region="county:*",
          regionin="state:46") %>%
  
  #assign location type to county
  mutate(locationtype='County') %>%
  
  #add in county name from fips codes, remove word 'county', add in state name
  left_join(fips,by=c('county'='county_code','state'='state_code')) %>% 
  mutate(county=gsub("\\s*\\w*$", "", county.y)) %>%
  
  #calculate relative SE
  mutate(relative_se=((S2701_C05_001M/1.645)/S2701_C05_001E)*100) %>%
  mutate(keep=if_else(relative_se>30,0,1)) %>%
  
  #identify the counties higher than overall using lower CI bound
  mutate(lower_estimate=S2701_C05_001E-S2701_C05_001M) %>%
  mutate(higher_than_overall=if_else(lower_estimate>9.9,1,0))


write.csv(countydata,file=paste0("/Users/xannaburg/Documents/KidsCountData/Output/myanalysis/southdakota_nhi_bycounty.csv"),row.names=FALSE)


```


### County Data for Poverty (B17024)
```{r}
countydata2 <- getCensus(name="acs/acs5",
          vintage=2022,
          key=Sys.getenv("CENSUS_API_KEY"),
          vars=c("B17024_042E","B17024_043E","B17024_044E","B17024_045E","B17024_046E",
                  "B17024_055E","B17024_056E","B17024_057E","B17024_058E","B17024_059E",
                  "B17024_068E","B17024_069E","B17024_070E","B17024_071E","B17024_072E",
                  "B17024_081E","B17024_082E","B17024_083E","B17024_084E","B17024_085E",
                  "B17024_094E","B17024_095E","B17024_096E","B17024_097E","B17024_098E"),
          region="county:*",
          regionin="state:46") %>%
  
  #assign location type to county
  mutate(locationtype='County') %>%
  
  #add in county name from fips codes, remove word 'county', add in state name
  left_join(fips,by=c('county'='county_code','state'='state_code')) %>% 
  mutate(county=gsub("\\s*\\w*$", "", county.y)) %>%
  
  #create sums
  mutate(totalnumberbelow124=B17024_042E+B17024_043E+B17024_044E+B17024_045E+B17024_055E+B17024_056E+B17024_057E+B17024_058E+B17024_068E+B17024_069E+B17024_070E+B17024_071E+B17024_081E+B17024_082E+B17024_083E+B17024_084E+B17024_094E+B17024_095E+B17024_096E+B17024_097E,
         totalnumberbelow150=B17024_042E+B17024_043E+B17024_044E+B17024_045E+B17024_046E+B17024_055E+B17024_056E+B17024_057E+B17024_058E+B17024_059E+B17024_068E+B17024_069E+B17024_070E+B17024_071E+B17024_072E+B17024_081E+B17024_082E+B17024_083E+B17024_084E+B17024_085E+B17024_094E+B17024_095E+B17024_096E+B17024_097E+B17024_098E) %>%
  select(c(state,county,totalnumberbelow124,totalnumberbelow150))



write.csv(countydata2,file=paste0("/Users/xannaburg/Documents/KidsCountData/Output/myanalysis/southdakota_poverty_bycounty.csv"),row.names=FALSE)


```

